workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "ai.restorank.bridge"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Build debug APK
        script: |
          cd $CM_BUILD_DIR
          chmod +x gradlew
          ./gradlew assembleDebug
    
    artifacts:
      - app/build/outputs/**/*.apk
